### ISSUE TITLE
DDQ_detr环境搭建问题

### ISSUE THREAD

**Issue by susumjt** [jshilong/DDQ#19]
作者您好，我在搭建DDQ_detr环境时这一步
ln -s mmcv-2.0.0rc4/mmcv ./
会报错ln: failed to create symbolic link ‘./mmcv’: File exists。
好像是因为和文件夹“mmcv-2.0.0rc4/mmcv”重名了，请问这个符号链接的绝对位置应该放在哪里啊。
另外，mmdetection和mmengine还需要构建吗？

**Comment by desline4709** [comment]
请问您是怎么解决这个问题的？我完成了mmcv的编译后，没做软连接发现报错；然后回到根目录把mmcv软连接出来还是不行，然后回到mmcv-2.0.0rc4进行本地安装（pip install -v -e .)还是不行
