### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by praeclarumjj3** [jshilong/DDQ#4]
Hi, thanks for the inspiring work! Could you provide an estimate for when you plan to release the code and models?
Thanks

**Comment by jshilong** [comment]
It mainly depends on when the DDQ is accepted.
If all goes well, the code should be released in the near future (maybe July), but I promise that the code will be released (you can find that all the papers I participated in have released the code

**Comment by jshilong** [comment]
> Hi, thanks for the inspiring work! Could you provide an estimate for when you plan to release the code and models? Thanks

DDQ was accepted by CVPR2023, DDQ FCN and DDQ RCNN parts have been released, I will release DDQ DETR tomorrow, sorry for the long wait

**Comment by praeclarumjj3** [comment]
Congratulations on the acceptance! Looking forward to the code release :)
