### ISSUE TITLE
supplementary materials?

### ISSUE THREAD

**Issue by Project627** [jshilong/DDQ#5]
Sorry to disturb but where are the supplementary materials?

**Comment by jshilong** [comment]
Sorry for forgetting to upload it to arxiv and I will update a version recently

**Comment by PeiChiChen** [comment]
Hello, has the supplementary materials been uploaded? Thanks.

**Comment by jshilong** [comment]
> Hello, has the supplementary materials been uploaded? Thanks.

We will update the new version in the near future, including more of our new findings (stronger performance), this version will be a bit outdated, please stay tuned

**Comment by jshilong** [comment]
DDQ was accepted by CVPR 2023, I will upload the camera ready version recently with DDQ DETR part, sorry for the long wait

**Comment by eternaldolphin** [comment]
> 

when will the paper on arxiv be updated to the newest version

**Comment by jshilong** [comment]
> when will the paper on arxiv be updated to the newest version

Thanks for your interest, we may upload a new version or update the old version to arxiv this week.

**Comment by jshilong** [comment]
> > 
> 
> when will the paper on arxiv be updated to the newest version

We have released ddq to arxiv today
https://arxiv.org/abs/2303.12776
