### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by Smart-Bobo** [jshilong/DDQ#6]
Your research achieved SOTA on the target coco dataset, which is amazing. I am also a practitioner in the cv industry. I am very interested in your research, and I have tried to reproduce the code myself, but I have failed due to my limited ability. I really want to learn the network structure you wrote. Can you give me A code for reference, this repository is empty, or you can upload the code to the github repository, thank you very much

**Comment by jshilong** [comment]
Thanks for your appreciation.
But sorry, I can only upload the code after the DDQ is accepted.
If all goes well, the code should be released in the near future (maybe July), but I promise to release the code (you can find that all the papers I have participated in have released the code, please stay tuned to this project
