### ISSUE TITLE
anchor base 

### ISSUE THREAD

**Issue by zhu011** [jshilong/DDQ#9]
Very good work, if I want to add DDQ to an anchor anchor-based single-stage detection network, how do I need to change it, is it to add the detection header, if it is okay to add an angle regression, can you give some suggestions? Thank you.

**Comment by jshilong** [comment]
Thank you for your interest in our project. 

You will only need to make minor modifications to the DDQFCN head to make it compatible with anchor-based methods. Specifically, you need change to the anchor generator and modify the anchor shape related code. 

For the rotated head, please refer to https://github.com/open-mmlab/mmrotate/blob/main/configs/rotated_fcos/README.md. 

Overall, I believe these changes are fairly straightforward.

**Comment by zhu011** [comment]
Thanks for the answer, I'll try it
